### ISSUE TITLE
计算偏差好大

### ISSUE THREAD

**Issue by hktalent** [CntChen/tile-lnglat-transform#1]
var TileLnglatTransform = require('tile-lnglat-transform');
var TileLnglatTransformBaidu = TileLnglatTransform.TileLnglatTransformBaidu;
// x: '11587519.22', y: '3558281.28' 
var o = TileLnglatTransformBaidu.pointToLnglat(11587519.22,3558281.28);

**Comment by CntChen** [comment]
感谢提出issue！

`pointToLnglat` 是百度地图**平面坐标转经纬度坐标**。
主要参考文档为：百度地图API [MercatorProjection][MercatorProjection]和[PerspectiveProjection][PerspectiveProjection]

* 使用`tile-lnglat-transform`库

我运行你的代码得到的结果是：`{ lng: 104.091324, lat: 30.594729 }`

* 使用百度地图API 2.0测试

使用`MercatorProjection`和`PerspectiveProjection`的测试结果都为`{lng: 104.091324, lat: 30.594729}`
**跟使用`tile-lnglat-transform`库结果一致。**

测试截图：
!['baidu pointtolnglat'](https://raw.githubusercontent.com/CntChen/hetu-cntchen/master/intercourse/baidu-pointtolgnlat.png)
测试代码：
```js
// 先引入百度地图
    var projection = new BMap.MercatorProjection();
    var result_MercatorProjection = projection.pointToLngLat(new BMap.Pixel(11587519.22,3558281.28));
  console.log('result_MercatorProjection:', result_MercatorProjection);
    var projection = new BMap.PerspectiveProjection();
    var result_PerspectiveProjection = projection.pointToLngLat(new BMap.Pixel(11587519.22,3558281.28));
  console.log('result_PerspectiveProjection:', result_PerspectiveProjection);
```

以前百度平面坐标的定义是：
>在百度地图API中，平面坐标是以最大级别18级为基准的。就是说在18级下，平面坐标的一个单位就代表了屏幕上的1个像素。 -- [百度地图API详解之地图坐标系统][百度地图API详解之地图坐标系统]

我猜测，有可能是百度地图升级为4k分辨率带来的像素坐标问题。
请补充你得到你的计算值的过程和结果值，方便我根据你的过程和结果值来debug。

[MercatorProjection]:http://developer.baidu.com/map/reference/index.php?title=Class:%E5%9C%B0%E5%9B%BE%E7%B1%BB%E5%9E%8B%E7%B1%BB/MercatorProjection
[PerspectiveProjection]:http://developer.baidu.com/map/reference/index.php?title=Class:%E5%9C%B0%E5%9B%BE%E7%B1%BB%E5%9E%8B%E7%B1%BB/PerspectiveProjection
[百度地图API详解之地图坐标系统]:http://www.cnblogs.com/jz1108/archive/2011/07/02/2095376.html
