### ISSUE TITLE
请问，有瓦片下载工具推荐一下么？

### ISSUE THREAD

**Issue by kungfuboy** [CntChen/tile-lnglat-transform#10]
如题，谢谢~

**Comment by CntChen** [comment]
我比较久没有接触地图领域了, 以前是自己写代码下载的. 你可以再搜索一下. 如果可以自己编码, 前期工作比较多, 后期会有比较大的收益, 下载工具为了非技术人员的易用性, 数据获取后二次处理比较麻烦.
