### ISSUE TITLE
请教下谷歌地图上的短坐标如何转成长坐标呢？

### ISSUE THREAD

**Issue by laiyiyi** [CntChen/tile-lnglat-transform#12]
![image](https://user-images.githubusercontent.com/12541388/50078253-73b61580-0221-11e9-9cb2-08af1bb6e7c4.png)
请教下，比如截图上那个坐标，如何转成 -1.5094702805732376,52.40981128619181  这样的呢？

**Comment by CntChen** [comment]
看起来截图上的坐标是经纬度坐标，不知道`-1.5094702805732376,52.40981128619181`是什么坐标系？
