### ISSUE TITLE
能实现一下高德矢量图的行列号转换吗？

### ISSUE THREAD

**Issue by kekeqy** [CntChen/tile-lnglat-transform#15]
示例地址https://vdata.amap.com/tiles?mapType=normal&v=3&style=5&key=608d75903d29ad471362f8c58c550daf&rd=1&flds=building&t=17,106538,57144;17,106538,57143;17,106537,57144;17,106537,57143&lv=17
矢量图的行列号似乎是在瓦片坐标的基础上加密而来的。

**Comment by CntChen** [comment]
目前没有在研究地图方面的内容了, 对"行列号"这个概念不了解.
欢迎给该项目提交 MR.

**Comment by kekeqy** [comment]
大佬，打扰了！
