### ISSUE TITLE
关于地图转换

### ISSUE THREAD

**Issue by liujia1** [CntChen/tile-lnglat-transform#2]
我想问一下，如果输送的坐标点在国外，其实是不要转换的，这个程序附带地理位置判断吗？还是要应用自己判断是否坐标在天朝，是否需要调用这个坐标转换？

**Comment by CntChen** [comment]
这个库的`转换`是`瓦片坐标`和`经纬度坐标`的转换，不同地图服务商的转换是独立的，并没有考虑经纬度的偏移（加密）。
对于一个地图服务商，根据其瓦片地图的规则，一个经纬度在某个地图层级会对应一个瓦片和瓦片上的一个像素位置。这跟经纬度是否是偏移的，应该没有关系。

不同地图服务商之间的坐标转换，如`WGS84` 、`GCJ-02`、 `BD-09`的相互转换，才需要考虑是否在国内(是否需要加密)。另一个库[coordtransform][coordtransform]专注于方面，可以去了解一下。

[coordtransform]:https://github.com/wandergis/coordtransform
