### ISSUE TITLE
关于百度瓦片的疑问

### ISSUE THREAD

**Issue by zhang852774731** [CntChen/tile-lnglat-transform#21]
http://cntchen.github.io/2016/05/09/%E5%9B%BD%E5%86%85%E4%B8%BB%E8%A6%81%E5%9C%B0%E5%9B%BE%E7%93%A6%E7%89%87%E5%9D%90%E6%A0%87%E7%B3%BB%E5%AE%9A%E4%B9%89%E5%8F%8A%E8%AE%A1%E7%AE%97%E5%8E%9F%E7%90%86/
很幸运看到您写的这篇博客，解决了我很多疑问
但关于百度瓦片的计算，我还有一些不明白的地方。
博客中有一张百度地图level2的截图，很明显可以看到截图中地图部分不是正方形。那么百度平面坐标采用的是什么方式？如果是web墨卡托，那么应该是正方形才对

**Comment by CntChen** [comment]
这个图印象中我是爬取了某个级别的全部瓦片, 然后拼接出来的. 百度应该也是 web 墨卡托, 不过在顶部和底部部分(北极和南极)百度没有生成瓦片数据.

比如这个瓦片: http://online1.map.bdimg.com/onlinelabel/qt=tile&x=2&y=2&z=3

| ![](http://online1.map.bdimg.com/onlinelabel/qt=tile&x=2&y=2&z=3) |

level 3 的东北角, 可以看到北面应该有地图内容, 不过百度没有去渲染出来; 东面是不存在的区域(其实是地图的西边). 所以算上北面和南面, 百度地图应该是 web 墨卡托投影.

至于百度平面坐标的规则, 可以看下文章中给出的参考文章.
