### ISSUE TITLE
谷歌瓦片转换bug

### ISSUE THREAD

**Issue by allan8212** [CntChen/tile-lnglat-transform#22]
```javascript
const TileLnglatTransform = require('tile-lnglat-transform');
const TileLnglatTransformObj = TileLnglatTransform.TileLnglatTransformGoogle;

let tile = TileLnglatTransformObj.lnglatToTile(-180, 90, 0);

console.log(tile);
```
输出结果：
{ tileX: 0, tileY: -6 }

已知google的瓦片图是从0,0开始的，这个转换有问题。

**Comment by CntChen** [comment]
根据摩卡托投影的定义, 墨卡托对地球的映射并不包括南极北极. 准确来说, 其有效的维度范围是 `[-85.05112877980659，85.05112877980659]`.

维度使用 `90` 应该是不合法的输入. 

![image](https://user-images.githubusercontent.com/4598445/100541731-bb080600-3280-11eb-9c9f-a93674a0d53b.png)

测试了一下:
```js
TileLnglatTransformObj.lnglatToTile(-180, 85.05112877980659, 0); // { tileX: 0, tileY: 0 }, 边界内, 结果正确
TileLnglatTransformObj.lnglatToTile(-180, 85.06, 0) // { tileX: 0, tileY: -1 }, 边界外, 结果错误
```

**Comment by allan8212** [comment]
```javascript
let tile1 = TileLnglatTransformGoogle.lnglatToTile(-180, 85.05112877980659, 4);
let tile2 = TileLnglatTransformGoogle.lnglatToTile(180, -85.05112877980659, 4);

console.log(tile1, tile2);
```
得到结果：{ tileX: 0, tileY: 0 } { tileX: 16, tileY: 15 }

但是 http://mt1.google.cn/vt/lyrs=m&x=16&y=15&z=4 报400错误，
实际 http://mt1.google.cn/vt/lyrs=m&x=15&y=15&z=4 可以访问，
所以这个右下角的边界计算是不是有误差呢，另外是否可以考虑加入自动修正边界值

**Comment by CntChen** [comment]
感谢反馈. 确实有问题: 正常是向下取值, 180的经度刚好到边界. 已经修复.
