### ISSUE TITLE
了解船讯网的海图数据怎么进行坐标转换么

### ISSUE THREAD

**Issue by bluesky4485** [CntChen/tile-lnglat-transform#4]
船讯网的偏移貌似还比较大，不清楚怎么换算啊，能抽空研究下么？

**Comment by CntChen** [comment]
没有时间去研究，看船讯网好像是用了 google map，可以试下使用 google map 的转换。
你也可以做个最简 demo，更好地表达你的问题，这样其他人也可以直接做测试。
