### ISSUE TITLE
百度地图坐标转换成pixel 出现x = 256 或者 y=256， 溢出？

### ISSUE THREAD

**Issue by lizecn** [CntChen/tile-lnglat-transform#5]
zoom level 10 
百度坐标 {lng: 120.097447, lat: 31.780346}
返回pixel {pixelX: 256, pixelY: 163}
tile 大小 256 x 256 x或者y 0-255， 转换后256是不是溢出了？

**Comment by CntChen** [comment]
感谢测试，应该是边界问题，我跟进一下。

**Comment by lizecn** [comment]
另外还发现tile 中x 或者 y 有正负1 pixel的误差，这个误差在level 10 情况下， 造成的偏移量还是不容忽视的。 可能跟上述的issue相关。

**Comment by lizecn** [comment]
var pixelX = Math.round(x * this._getMapSize(level) * 256 % 256);
 var pixelY = Math.round(y * this._getMapSize(level) * 256 % 256);

两行使用了round 进行了向上取整， 所以有256的出现了。 改成 
Math.floor(y * this._getMapSize(level) * 256 % 256); 可能会解决问题， 
小小思路， 希望lz 尽快解决这个问题。

**Comment by CntChen** [comment]
对，就是这个问题．用 Math.round 是有问题的．会导致取值区间变为 [0, 256]，一共 257 个取值.
用 Math.floor 是对的，取值区间为 [0, 255]，一共 256 个取值.
已经修复了，其他地图的转换也存在这个问题，也一并修复了．
