### ISSUE TITLE
请问瓦片地图该如何制作呢？

### ISSUE THREAD

**Issue by troyz** [CntChen/tile-lnglat-transform#7]
比如说我们有一张故宫的图片，想要根据这张图片来制作不同缩放等级下的瓦片地图，该怎样制作呢？

**Comment by CntChen** [comment]
瓦片地图是将地图等级化，每个等级下对地图进行切割。如果要自行制作，需要考虑三个点：
* 图片等级化和切割方式
* 瓦片化后的图片查询接口
* 展示瓦片化的图片

我没有实际研究，你可以参考： http://www.maptiler.com/
或使用关键字在 google 搜索： `make tile map from image`
