### ISSUE TITLE
pixelToLnglat 精确度问题

### ISSUE THREAD

**Issue by troyz** [CntChen/tile-lnglat-transform#8]
Hi,
发现`pixelToLnglat`计算出来的坐标跟原始坐标有些差异：

``` javascript
// 测试代码
var lnglat = {
  lng: 111.653157,
  lat: 40.754325
};
var level = 16;
var tile_baidu = TileLnglatTransformBaidu.lnglatToTile(lnglat.lng, lnglat.lat, level);
var pixel_baidu = TileLnglatTransformBaidu.lnglatToPixel(lnglat.lng, lnglat.lat, level);
var lnglat_baidu = TileLnglatTransformBaidu.pixelToLnglat(pixel_baidu.pixelX, pixel_baidu.pixelY, tile_baidu.tileX, tile_baidu.tileY, level);
console.log('to lnglat result:', lnglat_baidu);
```

> 输出：
> to lnglat result: { lng: 111.653123, lat: 40.754301 }

> 总结：原始坐标是`(111.653157, 40.754325)`，先转换成瓦片坐标+像素坐标，再转换回经纬度坐标，结果是`(111.653123, 40.754301)`，跟原始坐标相比存在误差，请问这个是什么原因造成的？

**Comment by CntChen** [comment]
这是正常情况，先转换成瓦片坐标+像素坐标，再转换回经纬度坐标，是存在误差的。

误差原因：
1. 原始经纬度坐标是连续的实数
2. 一个瓦片里面的像素坐标是不连续的整数 ([0, 255])
3. 经纬度坐标转换得到的像素坐标，其实是一个连续实数映射为一个不连续整数，**是做了四舍五入得到整数的，所以转换回去会丢失小数部分的像素坐标**
4. 因为做了四舍五入，误差有正有负**误差大小不会超过该地图等级下的一个像素坐标实际距离的 1/2**.

**Comment by troyz** [comment]
@CntChen 好的，谢谢解答。

问个其他的问题，按照现有的逻辑，是否可以计算19，20，21级的瓦片坐标？（因为百度只提供18级以下的瓦片，18级以上的不知道如何验证）

**Comment by CntChen** [comment]
百度的自己定义一种叫[`平面坐标`][百度地图API详解之地图坐标系统]的概念，以18级为基准。
所以超过18级的转换我不确定，你可以测试一下。
其他地图类型应该是可以的。

[百度地图API详解之地图坐标系统]: http://www.cnblogs.com/jz1108/archive/2011/07/02/2095376.html
