### ISSUE TITLE
经纬度转切片的公式与谷歌实测不符合

### ISSUE THREAD

**Issue by everywan** [CntChen/tile-lnglat-transform#9]
测试数据：阙左门 的经纬度地址
````
double lng = 116.3977300859833;
double lat = 39.91371035156561;
````
使用博客中的公式，在　zoom=18 时，算出的结果为　`{'tileX': 107915,'tileY': 115198}`，但是正常的值应该是`x=107915&y=49662`也就是说对于维度的计算是错误的。
以下是我实现的方法，使用博客中的公式：(python)
````
    n = math.pow(2, int(zoom))
    xtile = ((lng_deg + 180) / 360) * n
    lat_rad = lat_deg * math.pi/180
    fenzi = math.log(math.tan(lat_rad) + 1 / math.cos(lat_rad))
    ytile = (1.0 - ( fenzi/(math.pi*2) ) ) * n
````
以下是可得出与谷歌一致的公式：（java，lon算出的是正确的所以不再贴上）
````
double sinLat = Math.sin(lat * Math.PI / 180.0);
double drow = (2.0 - Math.log((1 + sinLat) / (1 - sinLat)) / Math.PI) * maxTileNumber / 4;
````
而且，使用下面这个转换出的切片，在使用博客提供的切片转经纬度的公式，得到的经纬度是正确的测试经纬度。
etc:
我实现的Python代码链接：`https://github.com/everywan/Everywan.Study/blob/76a889f7f8a53371a1e25d88bb2f4d5d8bd0ab64/Lib/tile2lonlat.py`

**Comment by CntChen** [comment]
感谢提 issue!

博客里面的公式错了, 应该修改为:
```py
lat_rad = lat_deg * math.pi/180
fenzi = math.log(math.tan(lat_rad) + 1 / math.cos(lat_rad))
ytile = (0.5 - ( fenzi/(math.pi*2) ) ) * n
```
**`1.0` 修改为 `0.5`.**[博文中已经修改过来][坐标转换公式], 这个库的源码测试通过, 代码是对的.

你提出的公式也是正确的, 两种公式形式其实是等价的, 可以看这里: [代码][公式等价].


P.S. 测试时候我使用的 zoom=17, 你的描述中是用了 18, 难道是另外一个 bug?

[坐标转换公式]: https://cntchen.github.io/2016/05/09/%E5%9B%BD%E5%86%85%E4%B8%BB%E8%A6%81%E5%9C%B0%E5%9B%BE%E7%93%A6%E7%89%87%E5%9D%90%E6%A0%87%E7%B3%BB%E5%AE%9A%E4%B9%89%E5%8F%8A%E8%AE%A1%E7%AE%97%E5%8E%9F%E7%90%86/#坐标转换公式
[公式等价]: https://github.com/CntChen/tile-lnglat-transform/blob/master/src/transform-class-slippy.js#L44

**Comment by everywan** [comment]
ｚｏｏｍ那个是因为我从１开始的，没有问题的
